export default {
    200: "/Images/thunderstorms-rain.svg",
    201: "/Images/thunderstorms-rain.svg",
    202: "/Images/thunderstorms-rain.svg",
    210: "/Images/thunderstorms.svg",
    211: "/Images/thunderstorms.svg",
    212: "/Images/thunderstorms.svg",
    221: "/Images/thunderstorms.svg",
    230: "/Images/thunderstorms-rain.svg",
    231: "/Images/thunderstorms-rain.svg",
    232: "/Images/thunderstorms-rain.svg",

    300: "/Images/drizzle.svg",
    301: "/Images/drizzle.svg",
    302: "/Images/drizzle.svg",
    310: "/Images/drizzle.svg",
    311: "/Images/drizzle.svg",
    312: "/Images/drizzle.svg",
    313: "/Images/drizzle.svg",
    314: "/Images/drizzle.svg",
    321: "/Images/drizzle.svg",

    500: "/Images/rain.svg",
    501: "/Images/rain.svg",
    502: "/Images/rain.svg",
    503: "/Images/rain.svg",
    504: "/Images/rain.svg",
    511: "/Images/rain.svg",
    520: "/Images/rain.svg",
    521: "/Images/rain.svg",
    522: "/Images/rain.svg",
    531: "/Images/rain.svg",

    600: "/Images/snow.svg",
    601: "/Images/snow.svg",
    602: "/Images/snow.svg",
    611: "/Images/snow.svg",
    612: "/Images/snow.svg",
    613: "/Images/snow.svg",
    615: "/Images/snow.svg",
    616: "/Images/snow.svg",
    620: "/Images/snow.svg",
    621: "/Images/snow.svg",
    622: "/Images/snow.svg",

    701: "/Images/mist.svg",
    711: "/Images/smoke.svg",
    721: "/Images/haze.svg",
    731: "/Images/dust-wind.svg",
    741: "/Images/fog.svg",
    751: "/Images/dust-wind.svg",
    761: "/Images/dust.svg",
    762: "/Images/dust.svg",
    771: "/Images/dust.svg",
    781: "/Images/tornado.svg",

    800: "/Images/clear-day.svg",
    801: "/Images/cloudy.svg",
    802: "/Images/cloudy.svg",
    803: "/Images/overcast.svg",
    804: "/Images/overcast.svg",
};